stages:
  - build
  - deploy_gcp

build_images:
  stage: build
  image: docker:20.10.16

  services:
    - docker:20.10.16-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  
  script:
    - docker build -t image app/.
    - docker push image

deploy_gcp:
  stage: deploy_gcp
  needs:
    - build_images
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY usuario@$SSH_SERVER "sudo rm -Rf ./app-cicd-kube && sudo git clone repositoriogitlab && cd app-cicd-kube && sudo chmod +x ./script.sh && ./script.sh"
